server:
  port: 8081
spring:
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/microservice
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      max-lifetime: 30000
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    show-sql: true
    generate-ddl: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE